[[redirects]]
  from = "/"
  to = "/core/quickstart"
  status = 307 # temporary redirect
  force = false

[[redirects]]
  from = "/docs"
  to = "/core/quickstart"
  status = 307 # temporary redirect
  force = false